name: posta
description: "A simple posting app implemented with riverpod"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  go_router: ^13.2.2
  firebase_core: ^2.27.2
  firebase_auth: ^4.19.0
  firebase_storage: ^11.6.11
  cloud_firestore: ^4.15.10
  uuid: ^4.3.3
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.7
  image: ^4.1.7
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  collection: ^1.18.0
  intl: ^0.19.0
  video_thumbnail: ^0.5.3
  video_player: ^2.8.3
  lottie: ^3.1.0
  share_plus: ^8.0.2
  url_launcher: ^6.2.5
  flutter_facebook_auth: ^6.1.1
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/android/ic_launcher.png"
  image_path_ios: "assets/ios/AppIcon@3x.png"
  adaptive_icon_background: "assets/android/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/android/ic_launcher_foreground.png"
  adaptive_icon_monochrome: "assets/android/ic_launcher_monochrome.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/ios/AppIcon@3x.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/posta_logo.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/mail.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each app in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
