// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA11u4fQry5TvTvHjG7l8PTdHhKE46_gus',
    appId: '1:586036629606:web:2609bce9fff36c0fe15da7',
    messagingSenderId: '586036629606',
    projectId: 'posta-9377a',
    authDomain: 'posta-9377a.firebaseapp.com',
    storageBucket: 'posta-9377a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4RNIt2__AaTo3UeVuPntO5ryT9ofK1qI',
    appId: '1:586036629606:android:6a7a4c0369698662e15da7',
    messagingSenderId: '586036629606',
    projectId: 'posta-9377a',
    storageBucket: 'posta-9377a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3J_IUBrshfyNhwqbtKgUKzV2e9ykimR8',
    appId: '1:586036629606:ios:965a5d3757640421e15da7',
    messagingSenderId: '586036629606',
    projectId: 'posta-9377a',
    storageBucket: 'posta-9377a.appspot.com',
    iosBundleId: 'com.example.posta',
  );
}
